### ISSUE TITLE
关于CDN目录刷新的问题

### ISSUE THREAD

**Issue by airinghost** [sylingd/tencent-cos-and-cdn-action#1]
![981C74BE-8751-44C5-BDE1-56C9B0450799](https://user-images.githubusercontent.com/78188675/169630198-e81e35a1-1371-403c-9b77-fcc04d097b9f.jpeg)

如图，全部文件已经「URL刷新」完成了，但查看刷新记录时，发现这里多出了一个「目录刷新」的操作（我感觉好像不是必需的），而且还是连续两条 // 斜杠（有些怪怪的）。

**Comment by sylingd** [comment]
能否提供一下配置中的cdn_prefix内容和clean内容？

**Comment by airinghost** [comment]
> 能否提供一下配置中的cdn_prefix内容和clean内容？

```
      - name: Tencent COS and CDN
        uses: sylingd/tencent-cos-and-cdn-action@v1
        with:
          secret_id: 
          secret_key: 
          cos_bucket: 
          cos_region: 
          cos_accelerate: false
          cdn_prefix: https://zhangjet.com/
          local_path: public
          remote_path: /
          clean: true
```
